// Mocks generated by Mockito 5.4.6 from annotations
// in f_term/test/features/term/term_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:f_term/src/common/services/terminal_service.dart' as _i3;
import 'package:f_term/src/features/term/models/terminal_command_result_model.dart'
    as _i2;
import 'package:f_term/src/features/term/repositories/terminal_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTerminalCommandResultModel_0 extends _i1.SmartFake
    implements _i2.TerminalCommandResultModel {
  _FakeTerminalCommandResultModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TerminalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTerminalService extends _i1.Mock implements _i3.TerminalService {
  MockTerminalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> executeCommand(String? command) =>
      (super.noSuchMethod(
            Invocation.method(#executeCommand, [command]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#executeCommand, [command]),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [TerminalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTerminalRepository extends _i1.Mock
    implements _i6.TerminalRepository {
  MockTerminalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TerminalCommandResultModel> executeCommand(String? command) =>
      (super.noSuchMethod(
            Invocation.method(#executeCommand, [command]),
            returnValue: _i4.Future<_i2.TerminalCommandResultModel>.value(
              _FakeTerminalCommandResultModel_0(
                this,
                Invocation.method(#executeCommand, [command]),
              ),
            ),
          )
          as _i4.Future<_i2.TerminalCommandResultModel>);

  @override
  _i4.Stream<_i2.TerminalCommandResultModel> executeCommandStream(
    String? command,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeCommandStream, [command]),
            returnValue: _i4.Stream<_i2.TerminalCommandResultModel>.empty(),
          )
          as _i4.Stream<_i2.TerminalCommandResultModel>);
}
